version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: dist  # use 'build' if you're using Create React App
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
