name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AWS CLI and EB CLI
        run: |
          pip install awsebcli

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd backend
          zip -r ../app.zip .
          cd ..
          aws elasticbeanstalk update-environment \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "build-${GITHUB_RUN_ID}" \
            --description "Deployed from GitHub Actions" \
            --region "${{ secrets.AWS_REGION }}" \
            --option-settings file://backend/.ebextensions/options.json || true
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "build-${GITHUB_RUN_ID}" \
            --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ github.repository_owner }}",S3Key="app.zip" \
            --region "${{ secrets.AWS_REGION }}"
